// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"time"
)

type Link struct {
	// uuidv7
	ID []byte
	// 租户id
	TenantID []byte
	// 用户id,审计用
	UserID []byte
	// 短链接
	ShortCode string
	// 原链接
	OriginalUrl string
	// 创建时间
	CreatedAt time.Time
	// 过期时间
	ExpiresAt *time.Time
}
