// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package model

import (
	"context"
	"time"
)

const CreateShortLink = `-- name: CreateShortLink :exec
INSERT INTO links (
    id,tenant_id,user_id,short_code,original_url,created_at,expires_at
) VALUES (
    ?,?,?,?,?,?,?
)
`

type CreateShortLinkParams struct {
	ID          []byte
	TenantID    []byte
	UserID      []byte
	ShortCode   string
	OriginalUrl string
	CreatedAt   time.Time
	ExpiresAt   *time.Time
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) error {
	_, err := q.db.ExecContext(ctx, CreateShortLink,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const GetOriginalUrlByCode = `-- name: GetOriginalUrlByCode :one
SELECT id, tenant_id, user_id, short_code, original_url, created_at, expires_at FROM links WHERE short_code = ? AND (expires_at > ? OR expires_at IS NULL)
`

type GetOriginalUrlByCodeParams struct {
	ShortCode string
	ExpiresAt *time.Time
}

func (q *Queries) GetOriginalUrlByCode(ctx context.Context, arg GetOriginalUrlByCodeParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, GetOriginalUrlByCode, arg.ShortCode, arg.ExpiresAt)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
